
import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

const WordDownloadButton = () => {
  const { toast } = useToast();
  const [isCapturing, setIsCapturing] = useState(false);

  const extractContentFromIframe = (): string => {
    try {
      // Try to access the iframe content
      const iframe = document.querySelector('iframe[title="AI Travel Assistant"]') as HTMLIFrameElement;
      if (!iframe) {
        throw new Error('AI Assistant iframe not found');
      }

      // Since we can't access cross-origin iframe content directly,
      // we'll provide instructions for the user to copy the content
      return `
AI Travel Assistant Conversation Results

Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

INSTRUCTIONS FOR COMPLETE CONTENT CAPTURE:
To get your complete conversation with hyperlinks:

1. Scroll through your entire AI conversation in the chat window above
2. Select all the text in the conversation (Ctrl+A or Cmd+A)
3. Copy the selected text (Ctrl+C or Cmd+C)
4. Paste it into a Word document or text editor
5. Save the document for your records

CONVERSATION SUMMARY:
This session included personalized travel recommendations from the AI Travel Assistant covering:

• Accessible accommodations and facilities
• Transportation options with accessibility features  
• Destination-specific accessibility information
• Emergency contacts and resources
• Customized travel tips and recommendations
• Relevant website links and resources
• Step-by-step guidance for accessible travel planning

IMPORTANT LINKS TO REFERENCE:
• AccessiTravel Main Site: https://your-domain.com
• AI Travel Assistant: https://your-domain.com/ai-assistant
• Transportation Guide: https://your-domain.com/transportation
• Wheelchair Services: https://your-domain.com/wheelchair-services
• Destination Planner: https://your-domain.com/planner

NEXT STEPS:
1. Review the recommendations provided in your conversation
2. Visit the suggested websites and resources
3. Contact mentioned venues directly to confirm accessibility features
4. Plan your trip using the provided guidance
5. Return to the AI Assistant for additional questions

For the most up-to-date information and to continue planning, visit AccessiTravel.

---
Document generated by AccessiTravel AI Assistant
Visit us at: https://your-domain.com
Support: contact@your-domain.com

Note: This document provides a framework for your travel planning. 
Please refer to your actual conversation above for specific details, 
recommendations, and clickable links provided by the AI Assistant.
      `;
    } catch (error) {
      console.log('Could not access iframe content:', error);
      return `
AI Travel Assistant Session Summary

Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

IMPORTANT: To capture your complete conversation with all hyperlinks and recommendations:

1. In the AI chat window above, scroll to the top of your conversation
2. Select all conversation content (Ctrl+A or Cmd+A in the chat area)
3. Copy the selected text (Ctrl+C or Cmd+C)  
4. Paste into a new Word document for complete preservation of links and formatting

This document serves as a backup summary of your AI Travel Assistant session.

SESSION OVERVIEW:
Your personalized consultation covered accessible travel planning including:

✓ Destination-specific accessibility information
✓ Accommodation recommendations with accessibility features
✓ Transportation options and booking guidance
✓ Emergency contacts and local resources
✓ Custom tips based on your specific needs
✓ Direct links to relevant services and websites

RECOMMENDED ACTIONS:
□ Copy your full conversation from the chat window above
□ Save important links and contact information separately
□ Verify accessibility features directly with venues
□ Book accommodations and transportation in advance
□ Keep emergency contact information accessible during travel

ACCESSITRAVEL RESOURCES:
• Main Website: https://your-domain.com
• AI Travel Assistant: https://your-domain.com/ai-assistant  
• Transportation Guide: https://your-domain.com/transportation
• Wheelchair Services: https://your-domain.com/wheelchair-services
• Trip Planner: https://your-domain.com/planner
• Multi-Destination Planning: https://your-domain.com/multi-destination

For continued support and planning assistance, return to the AI Travel Assistant or explore our comprehensive destination guides.

---
Generated by AccessiTravel AI Assistant
Contact: support@accessitravel.com
Website: https://your-domain.com
      `;
    }
  };

  const handleDownload = async () => {
    setIsCapturing(true);
    
    try {
      // Get the conversation content
      const conversationContent = extractContentFromIframe();
      
      // Create enhanced document content
      const documentContent = `AI TRAVEL ASSISTANT - COMPLETE SESSION REPORT
${'='.repeat(60)}

${conversationContent}

${'='.repeat(60)}
END OF REPORT

Generated: ${new Date().toLocaleString()}
Platform: AccessiTravel AI Assistant
Session ID: ${Date.now()}
      `;

      // Create a more properly formatted blob for Word
      const blob = new Blob([documentContent], {
        type: 'application/msword'
      });

      // Create download link
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `AccessiTravel_AI_Session_${new Date().toISOString().split('T')[0]}_${Date.now()}.doc`;
      
      // Trigger download
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      toast({
        title: "Session Report Downloaded!",
        description: "Your AI travel session has been saved. Follow the instructions in the document to capture your complete conversation with hyperlinks.",
        duration: 6000,
      });
    } catch (error) {
      console.error('Download error:', error);
      toast({
        title: "Download Error",
        description: "There was an issue creating your document. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsCapturing(false);
    }
  };

  return (
    <Button 
      onClick={handleDownload}
      variant="outline" 
      className="flex items-center gap-2"
      disabled={isCapturing}
    >
      <Download className="w-4 h-4" />
      {isCapturing ? 'Generating...' : 'Download Session Report'}
    </Button>
  );
};

export default WordDownloadButton;
